{
	"version": 1707409958,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/player-sheet0.png",
		"images/player-sheet1.png",
		"images/ground.png",
		"images/background.png",
		"images/tree-sheet0.png",
		"images/platform1-sheet0.png",
		"images/platform2-sheet0.png",
		"images/door-sheet0.png",
		"images/door-sheet1.png",
		"images/coin-sheet0.png",
		"images/coin-sheet1.png",
		"images/enemy-sheet0.png",
		"images/enemy-sheet1.png",
		"images/bullet-sheet0.png",
		"images/hp_bar.png",
		"images/btn_buy-sheet0.png",
		"images/newgame_btn-sheet0.png",
		"images/continue_btn-sheet0.png",
		"images/exit_btn-sheet0.png",
		"images/check_point-sheet0.png",
		"images/menu_btn-sheet0.png",
		"images/load_btn-sheet0.png",
		"images/mute_btn-sheet0.png",
		"media/coin.m4a",
		"media/coin.ogg",
		"media/run.m4a",
		"media/run.ogg",
		"media/shoot.m4a",
		"media/shoot.ogg",
		"media/background music.m4a",
		"media/background music.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}